[package]
name = "ancs4linux"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
zbus = "2.0"
zvariant = "2.8"
log = "0.4"
env_logger = "0.9"
async-trait = "0.1"
